### ISSUE TITLE
PRs / Shared Maintenance / Fork

### ISSUE THREAD

**Issue by techman83** [dieki-n/Octoprint-Filament-Scale#14]
@dieki-n I've started making changes to my own fork, now I could just release with a new title (Filament Scale Reborn or something more creative..), but if you'd like to be involved I will formulate some PRs. Alternatively, happy to take the name and continue the awesome work you've already done.

I've got it working on my printer with only a few tweaks, so awesome work!

I've got a concept that might alleviate #3 / #11, plus works in Python 3 solving #12 / #13

**Comment by mcbeenb** [comment]
I think it makes sense to formally fork this version and release. It's not perfect, but it seems to be working ok.

Thank you for bringing this forward!

**Comment by techman83** [comment]
Cool. I've been using it for a month now, readings are pretty good now that I've designed a better mount for my spool holder. I'll look into what's involved and go from there.

**Comment by techman83** [comment]
I've done a bunch of work in my fork and it should be pretty usable as is, I'll look into building a proper release workflow.

**Comment by techman83** [comment]
This was done and released
- https://github.com/techman83/Filament-Scale-Enhanced
- https://plugins.octoprint.org/plugins/filament_scale/
