### ISSUE TITLE
Possible Problem with Raspberry Pi 3 Model A+

### ISSUE THREAD

**Issue by TrinityCustomTech** [dieki-n/Octoprint-Filament-Scale#18]
We build customize 3D printers base on typical Ender style printers. One of our main features to add is a filament scale.

Have done 5 customized 3D printers using Raspberry Pi 3 Model B+ and Raspberry Pi 4s with the Filament Scale working great (even did an i3 Mini with a Raspberry Pi Zero 2 W and scale worked fine). The last 3 Printers we have built using Raspberry Pi 3 Model A+ are having massive NAN and weight errors (only 2 or 3 readings per 10 appear correct). If we connect a Raspberry Pi 4 (we have one set up to test non-Octoprint printers) the scale works great so it is not the cabling nor the HX711 wiring.

Looking at the clock signal with a scope between the Pi 4 and the Pi 3 Model A+ we find the Pi 4 clock running about 600-700 Hz. On the Pi 3 Model A+ it running about 60 Hz, which is below the spec for the HX711 (80 Hz).

Is there some way of increasing the clock rate when using the Pi 3 Model A+ or will this be a board not to use for Octoprint additions?

Thank you!

**Comment by dieki-n** [comment]
I do not have this set up with my printer anymore and no longer support this project.
