### ISSUE TITLE
suggestions to fix bad readings?

### ISSUE THREAD

**Issue by mark-hahn** [dieki-n/Octoprint-Filament-Scale#8]
The tare and calibrate (thanks for the soda can suggestion) work great.  But the when I put a full roll on I get 65 g.   I suspect it has to do with my hardware setup and I'm looking for advice.  What setup are other users here using on a raspi?

I'm using the cheap green board that came with the load cell.  I'm powering it with 3.3V because I don't want 5V on GPIO pins.  The specs on amazon say 2.7 to 5V for VCC.   I'm guessing it is probably clipping values due to using 3.3V. 

I've scoured the web and I'm getting tons of conflicting advice which on the whole is useless.  I guess I could buy a red sparkfun board but I hate to spend another $10.

**Comment by dieki-n** [comment]
I've been powering mine from 5v without issue. But that's very much an at-your-own-risk kind of thing and I can't recommend it without level shifting. Also, at least one person reported having issues when it was powered via 5v that disappeared when he switched to 3.3v. 

I suspect there may be quite a bit of variation between the different HX711 boards that you get on Ebay/Aliexpress.

**Comment by mark-hahn** [comment]
> I've been powering mine from 5v without issue.

It's possible the board is outputting a somewhat low voltage.  I'll drag out my scope.

**Comment by mark-hahn** [comment]
The hx711 datasheet says "Digital power supply (DVDD) should be the same power supply as the MCU power supply".  The green board schematic just hooks the only power supply pin called VCC to DVDD.  It's pretty clear the IO is VCC so I don't need to drag out the scope.

The sparkfun board allows the bridge to get 5V while data pins are 3.3V.  That is clearly the correct solution but for my 2 printers it will cost me $30 from amazon.

Maybe my current load cell or green board is bad.  I have a second one coming tomorrow for my 2nd printer so I'll find out tomorrow.

**Comment by mark-hahn** [comment]
This is extremely embarrassing but I had been typing in 35 grams instead of 390 for the soda can.  Call it a brain-fart.  Everything is working at 3.3V now.  Sorry to bother everyone.
